version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world circle ci"

workflows:
  my-workflow:
    jobs:
      - hello-job
